# Generated by Django 5.0.6 on 2024-07-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationdetail',
            name='level',
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='image_2',
            field=models.FileField(default='images/sw_1.jpeg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='image_3',
            field=models.FileField(default='images/sw_1.jpeg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='mkdetail',
            name='image_2',
            field=models.FileField(default='images/sw_1.jpeg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='mkdetail',
            name='image_3',
            field=models.FileField(default='images/sw_1.jpeg', upload_to='images/'),
        ),
    ]
