# Generated by Django 5.0.6 on 2024-06-24 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='paintings/')),
                ('price', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AboutPainting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image1', models.ImageField(upload_to='painting_details/')),
                ('image2', models.ImageField(upload_to='painting_details/')),
                ('image3', models.ImageField(upload_to='painting_details/')),
                ('image4', models.ImageField(upload_to='painting_details/')),
                ('painting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='painting.painting')),
            ],
        ),
    ]
